import os

import psycopg2
from dotenv import load_dotenv

load_dotenv()


def get_connection():
    database_url = os.environ["DATABASE_URL"]

    return psycopg2.connect(
        database_url,
        connect_timeout=10,
        sslmode="require"
    )


def create_tables():
    connection = get_connection()

    try:
        cursor = connection.cursor()

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS caregivers (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                mood TEXT NOT NULL,
                support_type TEXT NOT NULL,
                availability TEXT NOT NULL
            )
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS users (
                sender TEXT PRIMARY KEY,
                state TEXT NOT NULL,
                full_name TEXT,
                mood TEXT,
                support_type TEXT,
                availability TEXT
            )
        """)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS support_buddy_drafts (
                sender TEXT PRIMARY KEY,
                full_name TEXT,
                rdss_member TEXT,
                display_name TEXT,
                languages TEXT,
                caregiver_experience TEXT,
                support_types TEXT,
                availability TEXT,
                contact_methods TEXT,
                verification_required INTEGER DEFAULT 0,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                introduction TEXT,
                consent INTEGER NOT NULL DEFAULT 0,
                consent_text TEXT,
                consent_at TEXT
            )
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS support_buddy_applications (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sender TEXT UNIQUE NOT NULL,
                rdss_member TEXT,
                languages TEXT,
                availability TEXT,
                support_types TEXT,
                contact_methods TEXT,
                verification_required INTEGER DEFAULT 0,
                status TEXT NOT NULL DEFAULT 'pending',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                full_name TEXT,
                display_name TEXT,
                caregiver_experience TEXT,
                introduction TEXT,
                consent INTEGER NOT NULL DEFAULT 0,
                consent_text TEXT,
                consent_at TEXT,
                submitted_at TEXT,
                admin_notes TEXT NOT NULL DEFAULT '',
                verified_at TEXT,
                verified_by TEXT,
                reviewed_at TEXT,
                reviewed_by TEXT,
                review_version INTEGER NOT NULL DEFAULT 0
            )
        """)
                
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS match_requests (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                requester TEXT NOT NULL,
                caregiver_name TEXT NOT NULL,
                match_percentage INTEGER NOT NULL,
                status TEXT NOT NULL DEFAULT 'pending',
                buddy_id INTEGER,
                buddy_sender TEXT,
                support_type TEXT,
                availability TEXT,
                created_at TEXT,
                responded_at TEXT
            )
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS match_previews (
                requester TEXT PRIMARY KEY,
                buddy_id INTEGER NOT NULL,
                buddy_sender TEXT NOT NULL,
                caregiver_name TEXT NOT NULL,
                match_percentage INTEGER NOT NULL,
                support_type TEXT,
                availability TEXT
            )
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS buddy_request_inbox
            ON match_requests(buddy_sender, status, id)
        """)
        
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS conversation_messages (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sender TEXT NOT NULL,
                role TEXT NOT NULL,
                message TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
                # Admin review history
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS admin_review_events (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                application_id INTEGER NOT NULL,
                action TEXT NOT NULL,
                actor TEXT NOT NULL,
                notes TEXT NOT NULL DEFAULT '',
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # Admin login sessions
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS admin_sessions (
                token_hash TEXT PRIMARY KEY,
                credential_version TEXT NOT NULL,
                expires_at INTEGER NOT NULL
            )
        """)

        # Admin login attempt history
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS admin_login_attempts (
                attempted_at INTEGER NOT NULL
            )
        """)

        # Database indexes
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS admin_attempt_time
            ON admin_login_attempts(attempted_at)
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS admin_event_application
            ON admin_review_events(application_id)
        """)
        connection.commit()

    except Exception:
        connection.rollback()
        raise

    finally:
        connection.close()